### ISSUE TITLE
JREs for Linux ppc64le

### ISSUE THREAD

**Issue by HannesWell** [eclipse-justj/justj#12]
At the moment JustJ provides for Linux only artifacts for the `x86_64` and `aarch64` architecture. Some parts for Eclipse, for example SWT, are also provided for the `ppc64le` architecture on Linux.

Would it be much effort to provide JustJ JREs also for `ppc64le` on Linux?
Adoptium provides the corresponding binaries for Linux:
https://adoptium.net/de/temurin/archive/?version=17

AFAICT `ppc64le` is not very widely used, but for example for https://github.com/eclipse-platform/eclipse.platform.swt/pull/633 it would be convenient and those that use `ppc64le` would probably also be happy.

**Comment by HannesWell** [comment]
> I assume I would need another agent and for that I would need to ask for another resource pack. I don’t think there is much work involved otherwise.

That would be great. Agents should not be too much of a problem. At least the Releng Jenkins has the following two ppc agents:
- https://ci.eclipse.org/releng/computer/ppcle%2DbuildTest/
- https://ci.eclipse.org/releng/computer/ppcle%2Dtest/

And the first one is for example used to build the SWT natives for Linux ppc64le.

**Comment by merks** [comment]
I've prototyped the changes and have opened this issue to ask for an agent:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3050

**Comment by merks** [comment]
I think everything should be in place now, pending an agent being provided.  Here's I've done a build and emptied out the PPC64LE URL so that it's skipped...

Two assumptions I've made.  That I can use this label for the agent:

https://github.com/eclipse-justj/justj/blob/65870f52a74d2d9a7d0d71ab5f6ae10b580b14eb/releng/org.eclipse.justj.releng/Jenkinsfile#L374-L377

and that `uname -m` returns `ppc64le` on the agent.

https://github.com/eclipse-justj/justj/blob/65870f52a74d2d9a7d0d71ab5f6ae10b580b14eb/releng/org.eclipse.justj.releng/build-jre.sh#L79-L87

Of course I can easily adjust these if necessary.

**Comment by HannesWell** [comment]
Thanks Ed, you're awesome!

**Comment by merks** [comment]
They're available here for the first time:

https://download.eclipse.org/justj/www/download.eclipse.org.php?file=jres/17/downloads/20230428_1317

**Comment by HannesWell** [comment]
Thanks a lot again, I already updated https://github.com/eclipse-platform/eclipse.platform.swt/pull/633 and everything works well. 🚀 



> They're available here for the first time:
> 
> https://download.eclipse.org/justj/www/download.eclipse.org.php?file=jres/17/downloads/20230428_1317

I noticed there is already a newer version at https://download.eclipse.org/justj/?file=justj/jres/17/downloads/20230428_1804, I assume the latter should be preferred?

**Comment by merks** [comment]
They should be the same.  I didn't like the very long labels but I forgot that this only affects generate p2 IUs not the original packaged JREs so I should not have generated new ones...
