### ISSUE TITLE
Adoptium API and Jenkins Pipeline Matrix

### ISSUE THREAD

**Issue by HannesWell** [eclipse-justj/justj#13]
In the JustJ releng Jenkinsfile there are many hard-coded URLs to github downloads for different releases.

Adoptium provides an API, with which you can use more structured URLs that return redirects to the real locations of the artifacts:
- https://api.adoptium.net/
- https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc

With this API the URL could be composed on the fly just using input parameters for `java_version`, `os` and `architecture`:
```
https://api.adoptium.net/v3/binary/version/jdk-<java_version>/<os>/<architecture>/jdk/hotspot/normal/eclipse?project=jdk
```
Where version is for example `17.0.7%2B7` (`17.0.7+7` but URL encoded),
`os` is one of `linux`, `windows` or `mac` and
`architecture` is one of `x86_64`, `aarch64` or `ppc64le`

Those URLs only return temporary redirects to the actual location, but tools like curl can be configured to follow them automatically.

Together with [Jenkins matrix](https://www.jenkins.io/doc/book/pipeline/syntax/#declarative-matrix) there maybe could be many hard coded URLs and duplicated code less and adding only a new java version maybe would become as simple as just adding another element to a matrix axis.

But I have not yet looked into the details, I mainly wondered if you have considered using the Adoptium API and/or Jenkins matrix?

**Comment by merks** [comment]
Those are updated by the TemurinIndexer.    The indexer could be improved to use the API.  I ran it just today and noticed updates and am building them all. Tomorrow I’ll test the milestone builds before releasing them. 

So it’s not as hard coded as it looks.

**Comment by merks** [comment]
Adding support for ppc64le is a matter of updating the generator to add lines like this for it for the new variable

https://github.com/eclipse-justj/justj.tools/blob/9ab30f0744416109bb1ea0b033e2df8bfcf2df43/plugins/org.eclipse.justj.codegen/src/org/eclipse/justj/codegen/model/util/TemurinIndexer.java#L131-L139

It's very useful to see what if anything has changed and to see that URLs are actually available for all the expected os/arch combinations, e.g., 20.0.1 is missing ppc64le at the moment because it's still in progress.

This needs a few tweaks for that architecture:

https://github.com/eclipse-justj/justj/blob/master/releng/org.eclipse.justj.releng/build-jre.sh

As does this for the appropriate agent and such

https://github.com/eclipse-justj/justj/blob/master/releng/org.eclipse.justj.releng/Jenkinsfile

The indexer uses some horrible crawling logic that could be simplified via the Adoption API, but I'll revisit that if it ever stops working.
